// <auto-generated />
using System;
using CoinGraphic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinGraphic.Migrations
{
    [DbContext(typeof(ADDContext))]
    [Migration("20230820171408_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoinGraphic.Models.CoinHistoricVM", b =>
                {
                    b.Property<Guid>("CoinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("price_close")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price_high")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price_low")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price_open")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time_close")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time_open")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time_period_end")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("time_period_start")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trades_count")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("volume_traded")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoinId");

                    b.ToTable("CoinHistorics");
                });
#pragma warning restore 612, 618
        }
    }
}
